server:
  port: ${SERVER_PORT}

spring:
  application:
    name: core
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
springdoc:
  default-produces-media-type: application/json
  paths-to-exclude:
    - /springwolf/**
springwolf:
  use-fqn: false
  docket:
    base-package: io.github.gallardorubio.banksystem.core
    info:
      title: Bank System Core AsyncAPI
      version: 0.0.1
    servers:
      kafka-server:
        protocol: kafka
        host: ${KAFKA_HOST}:${KAFKA_PORT}