spring:
  application:
    name: core
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: core-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.{REGION}.amazonaws.com/{USER_POOL_ID}
springwolf:
  docket:
    base-package: io.github.gallardorubio.banksystem.core
    info:
      title: Bank System Core AsyncAPI
      version: 0.0.1
    servers:
      kafka-server:
        protocol: kafka
        host: localhost:9092