services:
  record:
    image: record
    build: 
      context: .
    container_name: record
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: optional:configtree:/run/secrets/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    secrets:
      - db-password

  db:
    image: postgres:alpine
    container_name: record-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: postgres
    secrets:
      - db-password

secrets:
  db-password:
    file: db-password