/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TransferRequest,
  TransferResponse
} from '../model';

import { customInstance } from '.././mutator/instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAllTransfers = (

 signal?: AbortSignal
) => {


      return customInstance<TransferResponse[]>(
      {url: `/api/v1/transfers`, method: 'GET', signal
    },
      );
    }




export const getGetAllTransfersQueryKey = () => {
    return [
    `/api/v1/transfers`
    ] as const;
    }


export const getGetAllTransfersQueryOptions = <TData = Awaited<ReturnType<typeof getAllTransfers>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTransfers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTransfersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTransfers>>> = ({ signal }) => getAllTransfers(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTransfers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllTransfersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTransfers>>>
export type GetAllTransfersQueryError = void


export function useGetAllTransfers<TData = Awaited<ReturnType<typeof getAllTransfers>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTransfers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTransfers>>,
          TError,
          Awaited<ReturnType<typeof getAllTransfers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTransfers<TData = Awaited<ReturnType<typeof getAllTransfers>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTransfers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTransfers>>,
          TError,
          Awaited<ReturnType<typeof getAllTransfers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTransfers<TData = Awaited<ReturnType<typeof getAllTransfers>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTransfers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllTransfers<TData = Awaited<ReturnType<typeof getAllTransfers>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTransfers>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllTransfersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const createTransfer = (
    transferRequest: TransferRequest,
 signal?: AbortSignal
) => {


      return customInstance<TransferResponse>(
      {url: `/api/v1/transfers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: transferRequest, signal
    },
      );
    }




export const getCreateTransferMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTransfer>>, TError,{data: TransferRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTransfer>>, TError,{data: TransferRequest}, TContext> => {

const mutationKey = ['createTransfer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTransfer>>, {data: TransferRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTransfer(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTransferMutationResult = NonNullable<Awaited<ReturnType<typeof createTransfer>>>
    export type CreateTransferMutationBody = TransferRequest
    export type CreateTransferMutationError = void

    export const useCreateTransfer = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTransfer>>, TError,{data: TransferRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTransfer>>,
        TError,
        {data: TransferRequest},
        TContext
      > => {
      return useMutation(getCreateTransferMutationOptions(options), queryClient);
    }
    export const getTransfer = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<TransferResponse>(
      {url: `/api/v1/transfers/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetTransferQueryKey = (id: string,) => {
    return [
    `/api/v1/transfers/${id}`
    ] as const;
    }


export const getGetTransferQueryOptions = <TData = Awaited<ReturnType<typeof getTransfer>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransfer>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTransferQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransfer>>> = ({ signal }) => getTransfer(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTransfer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTransferQueryResult = NonNullable<Awaited<ReturnType<typeof getTransfer>>>
export type GetTransferQueryError = void


export function useGetTransfer<TData = Awaited<ReturnType<typeof getTransfer>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransfer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransfer>>,
          TError,
          Awaited<ReturnType<typeof getTransfer>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransfer<TData = Awaited<ReturnType<typeof getTransfer>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransfer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransfer>>,
          TError,
          Awaited<ReturnType<typeof getTransfer>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTransfer<TData = Awaited<ReturnType<typeof getTransfer>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransfer>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTransfer<TData = Awaited<ReturnType<typeof getTransfer>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTransfer>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTransferQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






