/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DepositResponse,
  GetMyOperationsParams,
  InstallmentResponse,
  LoanResponse,
  PagedModelOperationEntryResponse,
  TransferResponse
} from '../model';

import { customInstance } from '.././mutator/instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getOperation = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<DepositResponse | InstallmentResponse | LoanResponse | TransferResponse>(
      {url: `/api/v1/operations/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetOperationQueryKey = (id: string,) => {
    return [
    `/api/v1/operations/${id}`
    ] as const;
    }


export const getGetOperationQueryOptions = <TData = Awaited<ReturnType<typeof getOperation>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperation>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOperationQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOperation>>> = ({ signal }) => getOperation(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOperation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOperationQueryResult = NonNullable<Awaited<ReturnType<typeof getOperation>>>
export type GetOperationQueryError = void


export function useGetOperation<TData = Awaited<ReturnType<typeof getOperation>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOperation>>,
          TError,
          Awaited<ReturnType<typeof getOperation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOperation<TData = Awaited<ReturnType<typeof getOperation>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOperation>>,
          TError,
          Awaited<ReturnType<typeof getOperation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOperation<TData = Awaited<ReturnType<typeof getOperation>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperation>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOperation<TData = Awaited<ReturnType<typeof getOperation>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperation>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOperationQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getOperationStatement = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<Blob>(
      {url: `/api/v1/operations/${id}/statement`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }




export const getGetOperationStatementQueryKey = (id: string,) => {
    return [
    `/api/v1/operations/${id}/statement`
    ] as const;
    }


export const getGetOperationStatementQueryOptions = <TData = Awaited<ReturnType<typeof getOperationStatement>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationStatement>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOperationStatementQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOperationStatement>>> = ({ signal }) => getOperationStatement(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOperationStatement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOperationStatementQueryResult = NonNullable<Awaited<ReturnType<typeof getOperationStatement>>>
export type GetOperationStatementQueryError = void


export function useGetOperationStatement<TData = Awaited<ReturnType<typeof getOperationStatement>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationStatement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOperationStatement>>,
          TError,
          Awaited<ReturnType<typeof getOperationStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOperationStatement<TData = Awaited<ReturnType<typeof getOperationStatement>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationStatement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOperationStatement>>,
          TError,
          Awaited<ReturnType<typeof getOperationStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOperationStatement<TData = Awaited<ReturnType<typeof getOperationStatement>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOperationStatement<TData = Awaited<ReturnType<typeof getOperationStatement>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOperationStatementQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getMyOperations = (
    params?: GetMyOperationsParams,
 signal?: AbortSignal
) => {


      return customInstance<PagedModelOperationEntryResponse>(
      {url: `/api/v1/operations/me`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetMyOperationsQueryKey = (params?: GetMyOperationsParams,) => {
    return [
    `/api/v1/operations/me`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMyOperationsQueryOptions = <TData = Awaited<ReturnType<typeof getMyOperations>>, TError = void>(params?: GetMyOperationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOperations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyOperationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyOperations>>> = ({ signal }) => getMyOperations(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyOperations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyOperationsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyOperations>>>
export type GetMyOperationsQueryError = void


export function useGetMyOperations<TData = Awaited<ReturnType<typeof getMyOperations>>, TError = void>(
 params: undefined |  GetMyOperationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOperations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOperations>>,
          TError,
          Awaited<ReturnType<typeof getMyOperations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyOperations<TData = Awaited<ReturnType<typeof getMyOperations>>, TError = void>(
 params?: GetMyOperationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOperations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOperations>>,
          TError,
          Awaited<ReturnType<typeof getMyOperations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyOperations<TData = Awaited<ReturnType<typeof getMyOperations>>, TError = void>(
 params?: GetMyOperationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOperations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyOperations<TData = Awaited<ReturnType<typeof getMyOperations>>, TError = void>(
 params?: GetMyOperationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyOperations>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyOperationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






