/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClientPersonalUpdateRequest,
  ClientRequest,
  ClientResponse,
  SecurityQuestionAnswersRequest,
  SecurityQuestionResponse,
  TrustedBankAccountResponse
} from '../model';

import { customInstance } from '.././mutator/instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const createClient = (
    clientRequest: ClientRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/clients`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clientRequest, signal
    },
      );
    }




export const getCreateClientMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClient>>, TError,{data: ClientRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createClient>>, TError,{data: ClientRequest}, TContext> => {

const mutationKey = ['createClient'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createClient>>, {data: ClientRequest}> = (props) => {
          const {data} = props ?? {};

          return  createClient(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateClientMutationResult = NonNullable<Awaited<ReturnType<typeof createClient>>>
    export type CreateClientMutationBody = ClientRequest
    export type CreateClientMutationError = void

    export const useCreateClient = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClient>>, TError,{data: ClientRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createClient>>,
        TError,
        {data: ClientRequest},
        TContext
      > => {
      return useMutation(getCreateClientMutationOptions(options), queryClient);
    }
    export const unlockAccount = (
    securityQuestionAnswersRequest: SecurityQuestionAnswersRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/clients/unlock`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: securityQuestionAnswersRequest, signal
    },
      );
    }




export const getUnlockAccountMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockAccount>>, TError,{data: SecurityQuestionAnswersRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unlockAccount>>, TError,{data: SecurityQuestionAnswersRequest}, TContext> => {

const mutationKey = ['unlockAccount'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlockAccount>>, {data: SecurityQuestionAnswersRequest}> = (props) => {
          const {data} = props ?? {};

          return  unlockAccount(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnlockAccountMutationResult = NonNullable<Awaited<ReturnType<typeof unlockAccount>>>
    export type UnlockAccountMutationBody = SecurityQuestionAnswersRequest
    export type UnlockAccountMutationError = void

    export const useUnlockAccount = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlockAccount>>, TError,{data: SecurityQuestionAnswersRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unlockAccount>>,
        TError,
        {data: SecurityQuestionAnswersRequest},
        TContext
      > => {
      return useMutation(getUnlockAccountMutationOptions(options), queryClient);
    }
    export const getClientPersonal = (

 signal?: AbortSignal
) => {


      return customInstance<ClientResponse>(
      {url: `/api/v1/clients/me`, method: 'GET', signal
    },
      );
    }




export const getGetClientPersonalQueryKey = () => {
    return [
    `/api/v1/clients/me`
    ] as const;
    }


export const getGetClientPersonalQueryOptions = <TData = Awaited<ReturnType<typeof getClientPersonal>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPersonal>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientPersonalQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientPersonal>>> = ({ signal }) => getClientPersonal(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientPersonal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientPersonalQueryResult = NonNullable<Awaited<ReturnType<typeof getClientPersonal>>>
export type GetClientPersonalQueryError = void


export function useGetClientPersonal<TData = Awaited<ReturnType<typeof getClientPersonal>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPersonal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientPersonal>>,
          TError,
          Awaited<ReturnType<typeof getClientPersonal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientPersonal<TData = Awaited<ReturnType<typeof getClientPersonal>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPersonal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientPersonal>>,
          TError,
          Awaited<ReturnType<typeof getClientPersonal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientPersonal<TData = Awaited<ReturnType<typeof getClientPersonal>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPersonal>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetClientPersonal<TData = Awaited<ReturnType<typeof getClientPersonal>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientPersonal>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientPersonalQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const updateClientPersonal = (
    clientPersonalUpdateRequest: ClientPersonalUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<ClientResponse>(
      {url: `/api/v1/clients/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: clientPersonalUpdateRequest, signal
    },
      );
    }




export const getUpdateClientPersonalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClientPersonal>>, TError,{data: ClientPersonalUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateClientPersonal>>, TError,{data: ClientPersonalUpdateRequest}, TContext> => {

const mutationKey = ['updateClientPersonal'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateClientPersonal>>, {data: ClientPersonalUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateClientPersonal(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateClientPersonalMutationResult = NonNullable<Awaited<ReturnType<typeof updateClientPersonal>>>
    export type UpdateClientPersonalMutationBody = ClientPersonalUpdateRequest
    export type UpdateClientPersonalMutationError = void

    export const useUpdateClientPersonal = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClientPersonal>>, TError,{data: ClientPersonalUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateClientPersonal>>,
        TError,
        {data: ClientPersonalUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateClientPersonalMutationOptions(options), queryClient);
    }
    export const getSecurityQuestionsCatalog = (

 signal?: AbortSignal
) => {


      return customInstance<SecurityQuestionResponse[]>(
      {url: `/api/v1/clients/security-questions`, method: 'GET', signal
    },
      );
    }




export const getGetSecurityQuestionsCatalogQueryKey = () => {
    return [
    `/api/v1/clients/security-questions`
    ] as const;
    }


export const getGetSecurityQuestionsCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSecurityQuestionsCatalogQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>> = ({ signal }) => getSecurityQuestionsCatalog(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSecurityQuestionsCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>>
export type GetSecurityQuestionsCatalogQueryError = void


export function useGetSecurityQuestionsCatalog<TData = Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>,
          TError,
          Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSecurityQuestionsCatalog<TData = Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>,
          TError,
          Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSecurityQuestionsCatalog<TData = Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSecurityQuestionsCatalog<TData = Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityQuestionsCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSecurityQuestionsCatalogQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTrustedBankAccounts = (

 signal?: AbortSignal
) => {


      return customInstance<TrustedBankAccountResponse[]>(
      {url: `/api/v1/clients/me/trusted-accounts`, method: 'GET', signal
    },
      );
    }




export const getGetTrustedBankAccountsQueryKey = () => {
    return [
    `/api/v1/clients/me/trusted-accounts`
    ] as const;
    }


export const getGetTrustedBankAccountsQueryOptions = <TData = Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrustedBankAccountsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrustedBankAccounts>>> = ({ signal }) => getTrustedBankAccounts(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrustedBankAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getTrustedBankAccounts>>>
export type GetTrustedBankAccountsQueryError = void


export function useGetTrustedBankAccounts<TData = Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrustedBankAccounts>>,
          TError,
          Awaited<ReturnType<typeof getTrustedBankAccounts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrustedBankAccounts<TData = Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrustedBankAccounts>>,
          TError,
          Awaited<ReturnType<typeof getTrustedBankAccounts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrustedBankAccounts<TData = Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTrustedBankAccounts<TData = Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrustedBankAccounts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrustedBankAccountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getMySecurityQuestions = (

 signal?: AbortSignal
) => {


      return customInstance<SecurityQuestionResponse[]>(
      {url: `/api/v1/clients/me/security-questions`, method: 'GET', signal
    },
      );
    }




export const getGetMySecurityQuestionsQueryKey = () => {
    return [
    `/api/v1/clients/me/security-questions`
    ] as const;
    }


export const getGetMySecurityQuestionsQueryOptions = <TData = Awaited<ReturnType<typeof getMySecurityQuestions>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySecurityQuestions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMySecurityQuestionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMySecurityQuestions>>> = ({ signal }) => getMySecurityQuestions(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMySecurityQuestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMySecurityQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getMySecurityQuestions>>>
export type GetMySecurityQuestionsQueryError = void


export function useGetMySecurityQuestions<TData = Awaited<ReturnType<typeof getMySecurityQuestions>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySecurityQuestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySecurityQuestions>>,
          TError,
          Awaited<ReturnType<typeof getMySecurityQuestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMySecurityQuestions<TData = Awaited<ReturnType<typeof getMySecurityQuestions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySecurityQuestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySecurityQuestions>>,
          TError,
          Awaited<ReturnType<typeof getMySecurityQuestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMySecurityQuestions<TData = Awaited<ReturnType<typeof getMySecurityQuestions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySecurityQuestions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMySecurityQuestions<TData = Awaited<ReturnType<typeof getMySecurityQuestions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySecurityQuestions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMySecurityQuestionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const removeTrustedBankAccount = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/clients/me/trusted-accounts/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getRemoveTrustedBankAccountMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeTrustedBankAccount>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeTrustedBankAccount>>, TError,{id: string}, TContext> => {

const mutationKey = ['removeTrustedBankAccount'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeTrustedBankAccount>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  removeTrustedBankAccount(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveTrustedBankAccountMutationResult = NonNullable<Awaited<ReturnType<typeof removeTrustedBankAccount>>>

    export type RemoveTrustedBankAccountMutationError = void

    export const useRemoveTrustedBankAccount = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeTrustedBankAccount>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeTrustedBankAccount>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getRemoveTrustedBankAccountMutationOptions(options), queryClient);
    }
