import os
from dotenv import load_dotenv

load_dotenv()

KAFKA_HOST = os.getenv("KAFKA_HOST")
KAFKA_PORT = os.getenv("KAFKA_PORT")
KAFKA_GROUP_ID = os.getenv("KAFKA_GROUP_ID")

BOOTSTRAP_SERVERS = f"{KAFKA_HOST}:{KAFKA_PORT}"

AWS_REGION = os.getenv("AWS_REGION")
AWS_BEDROCK_MODEL_ID = os.getenv("AWS_BEDROCK_MODEL_ID")

CORE_API_URL = os.getenv("CORE_API_URL")

COGNITO_CLIENT_ID = os.getenv("COGNITO_CLIENT_ID")
COGNITO_CLIENT_SECRET = os.getenv("COGNITO_CLIENT_SECRET")
COGNITO_DOMAIN = os.getenv("COGNITO_DOMAIN")
COGNITO_AGENTIC_SCOPE = os.getenv("COGNITO_AGENTIC_SCOPE")