/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BankAccountAnalyticsResponse,
  BankAccountResponse,
  GetBankAccountStatementParams,
  GetEntriesParams,
  GetMyBankAccountStatementParams,
  PagedModelBankAccountEntryResponse
} from '../model';

import { customInstance } from '.././mutator/instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getBankAccountStatement = (
    id: string,
    params?: GetBankAccountStatementParams,
 signal?: AbortSignal
) => {


      return customInstance<Blob>(
      {url: `/api/v1/bank-accounts/${id}/statement`, method: 'GET',
        params,
        responseType: 'blob', signal
    },
      );
    }




export const getGetBankAccountStatementQueryKey = (id: string,
    params?: GetBankAccountStatementParams,) => {
    return [
    `/api/v1/bank-accounts/${id}/statement`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetBankAccountStatementQueryOptions = <TData = Awaited<ReturnType<typeof getBankAccountStatement>>, TError = void>(id: string,
    params?: GetBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankAccountStatement>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBankAccountStatementQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBankAccountStatement>>> = ({ signal }) => getBankAccountStatement(id,params, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBankAccountStatement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBankAccountStatementQueryResult = NonNullable<Awaited<ReturnType<typeof getBankAccountStatement>>>
export type GetBankAccountStatementQueryError = void


export function useGetBankAccountStatement<TData = Awaited<ReturnType<typeof getBankAccountStatement>>, TError = void>(
 id: string,
    params: undefined |  GetBankAccountStatementParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankAccountStatement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankAccountStatement>>,
          TError,
          Awaited<ReturnType<typeof getBankAccountStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankAccountStatement<TData = Awaited<ReturnType<typeof getBankAccountStatement>>, TError = void>(
 id: string,
    params?: GetBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankAccountStatement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankAccountStatement>>,
          TError,
          Awaited<ReturnType<typeof getBankAccountStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankAccountStatement<TData = Awaited<ReturnType<typeof getBankAccountStatement>>, TError = void>(
 id: string,
    params?: GetBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankAccountStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBankAccountStatement<TData = Awaited<ReturnType<typeof getBankAccountStatement>>, TError = void>(
 id: string,
    params?: GetBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankAccountStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBankAccountStatementQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getMyBankAccount = (

 signal?: AbortSignal
) => {


      return customInstance<BankAccountResponse>(
      {url: `/api/v1/bank-accounts/me`, method: 'GET', signal
    },
      );
    }




export const getGetMyBankAccountQueryKey = () => {
    return [
    `/api/v1/bank-accounts/me`
    ] as const;
    }


export const getGetMyBankAccountQueryOptions = <TData = Awaited<ReturnType<typeof getMyBankAccount>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyBankAccountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBankAccount>>> = ({ signal }) => getMyBankAccount(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyBankAccountQueryResult = NonNullable<Awaited<ReturnType<typeof getMyBankAccount>>>
export type GetMyBankAccountQueryError = void


export function useGetMyBankAccount<TData = Awaited<ReturnType<typeof getMyBankAccount>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBankAccount>>,
          TError,
          Awaited<ReturnType<typeof getMyBankAccount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyBankAccount<TData = Awaited<ReturnType<typeof getMyBankAccount>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBankAccount>>,
          TError,
          Awaited<ReturnType<typeof getMyBankAccount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyBankAccount<TData = Awaited<ReturnType<typeof getMyBankAccount>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyBankAccount<TData = Awaited<ReturnType<typeof getMyBankAccount>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccount>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyBankAccountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getMyBankAccountStatement = (
    params?: GetMyBankAccountStatementParams,
 signal?: AbortSignal
) => {


      return customInstance<Blob>(
      {url: `/api/v1/bank-accounts/me/statement`, method: 'GET',
        params,
        responseType: 'blob', signal
    },
      );
    }




export const getGetMyBankAccountStatementQueryKey = (params?: GetMyBankAccountStatementParams,) => {
    return [
    `/api/v1/bank-accounts/me/statement`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMyBankAccountStatementQueryOptions = <TData = Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError = void>(params?: GetMyBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyBankAccountStatementQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBankAccountStatement>>> = ({ signal }) => getMyBankAccountStatement(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyBankAccountStatementQueryResult = NonNullable<Awaited<ReturnType<typeof getMyBankAccountStatement>>>
export type GetMyBankAccountStatementQueryError = void


export function useGetMyBankAccountStatement<TData = Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError = void>(
 params: undefined |  GetMyBankAccountStatementParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBankAccountStatement>>,
          TError,
          Awaited<ReturnType<typeof getMyBankAccountStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyBankAccountStatement<TData = Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError = void>(
 params?: GetMyBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBankAccountStatement>>,
          TError,
          Awaited<ReturnType<typeof getMyBankAccountStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyBankAccountStatement<TData = Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError = void>(
 params?: GetMyBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyBankAccountStatement<TData = Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError = void>(
 params?: GetMyBankAccountStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBankAccountStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyBankAccountStatementQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEntries = (
    params?: GetEntriesParams,
 signal?: AbortSignal
) => {


      return customInstance<PagedModelBankAccountEntryResponse>(
      {url: `/api/v1/bank-accounts/me/entries`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetEntriesQueryKey = (params?: GetEntriesParams,) => {
    return [
    `/api/v1/bank-accounts/me/entries`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetEntriesQueryOptions = <TData = Awaited<ReturnType<typeof getEntries>>, TError = void>(params?: GetEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntries>>> = ({ signal }) => getEntries(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntriesQueryResult = NonNullable<Awaited<ReturnType<typeof getEntries>>>
export type GetEntriesQueryError = void


export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = void>(
 params: undefined |  GetEntriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntries>>,
          TError,
          Awaited<ReturnType<typeof getEntries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = void>(
 params?: GetEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntries>>,
          TError,
          Awaited<ReturnType<typeof getEntries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = void>(
 params?: GetEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = void>(
 params?: GetEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEntriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getAnalytics = (

 signal?: AbortSignal
) => {


      return customInstance<BankAccountAnalyticsResponse>(
      {url: `/api/v1/bank-accounts/analytics`, method: 'GET', signal
    },
      );
    }




export const getGetAnalyticsQueryKey = () => {
    return [
    `/api/v1/bank-accounts/analytics`
    ] as const;
    }


export const getGetAnalyticsQueryOptions = <TData = Awaited<ReturnType<typeof getAnalytics>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalytics>>> = ({ signal }) => getAnalytics(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalytics>>>
export type GetAnalyticsQueryError = void


export function useGetAnalytics<TData = Awaited<ReturnType<typeof getAnalytics>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalytics>>,
          TError,
          Awaited<ReturnType<typeof getAnalytics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalytics<TData = Awaited<ReturnType<typeof getAnalytics>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalytics>>,
          TError,
          Awaited<ReturnType<typeof getAnalytics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalytics<TData = Awaited<ReturnType<typeof getAnalytics>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAnalytics<TData = Awaited<ReturnType<typeof getAnalytics>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






