/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetFraudRecordsParams,
  PagedModelFraudEntity
} from '../model';

import { customInstance } from '.././mutator/instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getFraudRecords = (
    params?: GetFraudRecordsParams,
 signal?: AbortSignal
) => {


      return customInstance<PagedModelFraudEntity>(
      {url: `/api/v1/fraud`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetFraudRecordsQueryKey = (params?: GetFraudRecordsParams,) => {
    return [
    `/api/v1/fraud`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetFraudRecordsQueryOptions = <TData = Awaited<ReturnType<typeof getFraudRecords>>, TError = void>(params?: GetFraudRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFraudRecords>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFraudRecordsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFraudRecords>>> = ({ signal }) => getFraudRecords(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFraudRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFraudRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof getFraudRecords>>>
export type GetFraudRecordsQueryError = void


export function useGetFraudRecords<TData = Awaited<ReturnType<typeof getFraudRecords>>, TError = void>(
 params: undefined |  GetFraudRecordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFraudRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFraudRecords>>,
          TError,
          Awaited<ReturnType<typeof getFraudRecords>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFraudRecords<TData = Awaited<ReturnType<typeof getFraudRecords>>, TError = void>(
 params?: GetFraudRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFraudRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFraudRecords>>,
          TError,
          Awaited<ReturnType<typeof getFraudRecords>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFraudRecords<TData = Awaited<ReturnType<typeof getFraudRecords>>, TError = void>(
 params?: GetFraudRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFraudRecords>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFraudRecords<TData = Awaited<ReturnType<typeof getFraudRecords>>, TError = void>(
 params?: GetFraudRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFraudRecords>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFraudRecordsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






