[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic"
version = "0.0.1"
authors = [
    { name = "gallardorubio" }
]
requires-python = ">=3.11"
dependencies = [
    "langgraph>=1.2.10",
    "langchain-core>=1.5.3",
    "confluent-kafka>=2.15.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "boto3>=1.43.66",
    "httpx>=0.28.1"
]