/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DepositRequest,
  DepositResolutionRequest,
  DepositResponse
} from '../model';

import { customInstance } from '.././mutator/instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAllDeposits = (

 signal?: AbortSignal
) => {


      return customInstance<DepositResponse[]>(
      {url: `/api/v1/deposits`, method: 'GET', signal
    },
      );
    }




export const getGetAllDepositsQueryKey = () => {
    return [
    `/api/v1/deposits`
    ] as const;
    }


export const getGetAllDepositsQueryOptions = <TData = Awaited<ReturnType<typeof getAllDeposits>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDeposits>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllDepositsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllDeposits>>> = ({ signal }) => getAllDeposits(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllDeposits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllDepositsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllDeposits>>>
export type GetAllDepositsQueryError = void


export function useGetAllDeposits<TData = Awaited<ReturnType<typeof getAllDeposits>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDeposits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDeposits>>,
          TError,
          Awaited<ReturnType<typeof getAllDeposits>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllDeposits<TData = Awaited<ReturnType<typeof getAllDeposits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDeposits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDeposits>>,
          TError,
          Awaited<ReturnType<typeof getAllDeposits>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllDeposits<TData = Awaited<ReturnType<typeof getAllDeposits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDeposits>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllDeposits<TData = Awaited<ReturnType<typeof getAllDeposits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllDeposits>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllDepositsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const createDeposit = (
    depositRequest: DepositRequest,
 signal?: AbortSignal
) => {


      return customInstance<DepositResponse>(
      {url: `/api/v1/deposits`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: depositRequest, signal
    },
      );
    }




export const getCreateDepositMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeposit>>, TError,{data: DepositRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createDeposit>>, TError,{data: DepositRequest}, TContext> => {

const mutationKey = ['createDeposit'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDeposit>>, {data: DepositRequest}> = (props) => {
          const {data} = props ?? {};

          return  createDeposit(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDepositMutationResult = NonNullable<Awaited<ReturnType<typeof createDeposit>>>
    export type CreateDepositMutationBody = DepositRequest
    export type CreateDepositMutationError = void

    export const useCreateDeposit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeposit>>, TError,{data: DepositRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDeposit>>,
        TError,
        {data: DepositRequest},
        TContext
      > => {
      return useMutation(getCreateDepositMutationOptions(options), queryClient);
    }
    export const getDeposit = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<DepositResponse>(
      {url: `/api/v1/deposits/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetDepositQueryKey = (id: string,) => {
    return [
    `/api/v1/deposits/${id}`
    ] as const;
    }


export const getGetDepositQueryOptions = <TData = Awaited<ReturnType<typeof getDeposit>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeposit>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDepositQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeposit>>> = ({ signal }) => getDeposit(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeposit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepositQueryResult = NonNullable<Awaited<ReturnType<typeof getDeposit>>>
export type GetDepositQueryError = void


export function useGetDeposit<TData = Awaited<ReturnType<typeof getDeposit>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeposit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeposit>>,
          TError,
          Awaited<ReturnType<typeof getDeposit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeposit<TData = Awaited<ReturnType<typeof getDeposit>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeposit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeposit>>,
          TError,
          Awaited<ReturnType<typeof getDeposit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeposit<TData = Awaited<ReturnType<typeof getDeposit>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeposit>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDeposit<TData = Awaited<ReturnType<typeof getDeposit>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeposit>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDepositQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const resolveDeposit = (
    id: string,
    depositResolutionRequest: DepositResolutionRequest,
 signal?: AbortSignal
) => {


      return customInstance<DepositResponse>(
      {url: `/api/v1/deposits/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: depositResolutionRequest, signal
    },
      );
    }




export const getResolveDepositMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveDeposit>>, TError,{id: string;data: DepositResolutionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof resolveDeposit>>, TError,{id: string;data: DepositResolutionRequest}, TContext> => {

const mutationKey = ['resolveDeposit'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveDeposit>>, {id: string;data: DepositResolutionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  resolveDeposit(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResolveDepositMutationResult = NonNullable<Awaited<ReturnType<typeof resolveDeposit>>>
    export type ResolveDepositMutationBody = DepositResolutionRequest
    export type ResolveDepositMutationError = void

    export const useResolveDeposit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveDeposit>>, TError,{id: string;data: DepositResolutionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resolveDeposit>>,
        TError,
        {id: string;data: DepositResolutionRequest},
        TContext
      > => {
      return useMutation(getResolveDepositMutationOptions(options), queryClient);
    }
    export const getEscalatedDeposits = (

 signal?: AbortSignal
) => {


      return customInstance<DepositResponse[]>(
      {url: `/api/v1/deposits/escalated`, method: 'GET', signal
    },
      );
    }




export const getGetEscalatedDepositsQueryKey = () => {
    return [
    `/api/v1/deposits/escalated`
    ] as const;
    }


export const getGetEscalatedDepositsQueryOptions = <TData = Awaited<ReturnType<typeof getEscalatedDeposits>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedDeposits>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEscalatedDepositsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEscalatedDeposits>>> = ({ signal }) => getEscalatedDeposits(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEscalatedDeposits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEscalatedDepositsQueryResult = NonNullable<Awaited<ReturnType<typeof getEscalatedDeposits>>>
export type GetEscalatedDepositsQueryError = void


export function useGetEscalatedDeposits<TData = Awaited<ReturnType<typeof getEscalatedDeposits>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedDeposits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEscalatedDeposits>>,
          TError,
          Awaited<ReturnType<typeof getEscalatedDeposits>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEscalatedDeposits<TData = Awaited<ReturnType<typeof getEscalatedDeposits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedDeposits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEscalatedDeposits>>,
          TError,
          Awaited<ReturnType<typeof getEscalatedDeposits>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEscalatedDeposits<TData = Awaited<ReturnType<typeof getEscalatedDeposits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedDeposits>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEscalatedDeposits<TData = Awaited<ReturnType<typeof getEscalatedDeposits>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedDeposits>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEscalatedDepositsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






