/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  LoanRequest,
  LoanResolutionRequest,
  LoanResponse
} from '../model';

import { customInstance } from '.././mutator/instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAllLoans = (

 signal?: AbortSignal
) => {


      return customInstance<LoanResponse[]>(
      {url: `/api/v1/loans`, method: 'GET', signal
    },
      );
    }




export const getGetAllLoansQueryKey = () => {
    return [
    `/api/v1/loans`
    ] as const;
    }


export const getGetAllLoansQueryOptions = <TData = Awaited<ReturnType<typeof getAllLoans>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLoans>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLoansQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLoans>>> = ({ signal }) => getAllLoans(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLoans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllLoansQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLoans>>>
export type GetAllLoansQueryError = void


export function useGetAllLoans<TData = Awaited<ReturnType<typeof getAllLoans>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLoans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLoans>>,
          TError,
          Awaited<ReturnType<typeof getAllLoans>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLoans<TData = Awaited<ReturnType<typeof getAllLoans>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLoans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLoans>>,
          TError,
          Awaited<ReturnType<typeof getAllLoans>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLoans<TData = Awaited<ReturnType<typeof getAllLoans>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLoans>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllLoans<TData = Awaited<ReturnType<typeof getAllLoans>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLoans>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllLoansQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const createLoan = (
    loanRequest: LoanRequest,
 signal?: AbortSignal
) => {


      return customInstance<LoanResponse>(
      {url: `/api/v1/loans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loanRequest, signal
    },
      );
    }




export const getCreateLoanMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLoan>>, TError,{data: LoanRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLoan>>, TError,{data: LoanRequest}, TContext> => {

const mutationKey = ['createLoan'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLoan>>, {data: LoanRequest}> = (props) => {
          const {data} = props ?? {};

          return  createLoan(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateLoanMutationResult = NonNullable<Awaited<ReturnType<typeof createLoan>>>
    export type CreateLoanMutationBody = LoanRequest
    export type CreateLoanMutationError = void

    export const useCreateLoan = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLoan>>, TError,{data: LoanRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLoan>>,
        TError,
        {data: LoanRequest},
        TContext
      > => {
      return useMutation(getCreateLoanMutationOptions(options), queryClient);
    }
    export const getLoan = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<LoanResponse>(
      {url: `/api/v1/loans/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetLoanQueryKey = (id: string,) => {
    return [
    `/api/v1/loans/${id}`
    ] as const;
    }


export const getGetLoanQueryOptions = <TData = Awaited<ReturnType<typeof getLoan>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoan>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLoanQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLoan>>> = ({ signal }) => getLoan(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLoan>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLoanQueryResult = NonNullable<Awaited<ReturnType<typeof getLoan>>>
export type GetLoanQueryError = void


export function useGetLoan<TData = Awaited<ReturnType<typeof getLoan>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoan>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoan>>,
          TError,
          Awaited<ReturnType<typeof getLoan>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLoan<TData = Awaited<ReturnType<typeof getLoan>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoan>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoan>>,
          TError,
          Awaited<ReturnType<typeof getLoan>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLoan<TData = Awaited<ReturnType<typeof getLoan>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoan>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLoan<TData = Awaited<ReturnType<typeof getLoan>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoan>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLoanQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const resolveLoan = (
    id: string,
    loanResolutionRequest: LoanResolutionRequest,
 signal?: AbortSignal
) => {


      return customInstance<LoanResponse>(
      {url: `/api/v1/loans/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: loanResolutionRequest, signal
    },
      );
    }




export const getResolveLoanMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveLoan>>, TError,{id: string;data: LoanResolutionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof resolveLoan>>, TError,{id: string;data: LoanResolutionRequest}, TContext> => {

const mutationKey = ['resolveLoan'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveLoan>>, {id: string;data: LoanResolutionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  resolveLoan(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResolveLoanMutationResult = NonNullable<Awaited<ReturnType<typeof resolveLoan>>>
    export type ResolveLoanMutationBody = LoanResolutionRequest
    export type ResolveLoanMutationError = void

    export const useResolveLoan = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveLoan>>, TError,{id: string;data: LoanResolutionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resolveLoan>>,
        TError,
        {id: string;data: LoanResolutionRequest},
        TContext
      > => {
      return useMutation(getResolveLoanMutationOptions(options), queryClient);
    }
    export const getEscalatedLoans = (

 signal?: AbortSignal
) => {


      return customInstance<LoanResponse[]>(
      {url: `/api/v1/loans/escalated`, method: 'GET', signal
    },
      );
    }




export const getGetEscalatedLoansQueryKey = () => {
    return [
    `/api/v1/loans/escalated`
    ] as const;
    }


export const getGetEscalatedLoansQueryOptions = <TData = Awaited<ReturnType<typeof getEscalatedLoans>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedLoans>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEscalatedLoansQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEscalatedLoans>>> = ({ signal }) => getEscalatedLoans(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEscalatedLoans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEscalatedLoansQueryResult = NonNullable<Awaited<ReturnType<typeof getEscalatedLoans>>>
export type GetEscalatedLoansQueryError = void


export function useGetEscalatedLoans<TData = Awaited<ReturnType<typeof getEscalatedLoans>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedLoans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEscalatedLoans>>,
          TError,
          Awaited<ReturnType<typeof getEscalatedLoans>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEscalatedLoans<TData = Awaited<ReturnType<typeof getEscalatedLoans>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedLoans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEscalatedLoans>>,
          TError,
          Awaited<ReturnType<typeof getEscalatedLoans>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEscalatedLoans<TData = Awaited<ReturnType<typeof getEscalatedLoans>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedLoans>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEscalatedLoans<TData = Awaited<ReturnType<typeof getEscalatedLoans>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEscalatedLoans>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEscalatedLoansQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






