/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { BankAccountEntryResponseOperationDirection } from './bankAccountEntryResponseOperationDirection';
import type { BankAccountEntryResponseOperationType } from './bankAccountEntryResponseOperationType';

export interface BankAccountEntryResponse {
  id?: string;
  operationId?: string;
  operationType?: BankAccountEntryResponseOperationType;
  description?: string;
  amount?: number;
  operationDirection?: BankAccountEntryResponseOperationDirection;
  createdAt?: string;
}
