/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export interface ClientResponse {
  name?: string;
  phone?: string;
  address?: string;
  nationality?: string;
  birthDate?: string;
  email?: string;
  taxId?: string;
  mfaEnabled?: boolean;
}
