/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export interface ClientPersonalUpdateRequest {
  name?: string;
  phone?: string;
  address?: string;
  nationality?: string;
  birthDate?: string;
  questionId: number;
  /** @minLength 1 */
  answer: string;
}
