/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { DepositResponseStatus } from './depositResponseStatus';
import type { OperationResponse } from './operationResponse';
import type { OperationStatusPhase } from './operationStatusPhase';

export type DepositResponse = OperationResponse & {
  id?: string;
  clientBankAccountId?: string;
  amount?: number;
  status?: DepositResponseStatus;
  statusHistory?: OperationStatusPhase[];
  createdAt?: string;
};
