/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export interface FraudEntity {
  id?: string;
  operationId?: string;
  clientId?: string;
  clientBankAccountId?: string;
  amount?: number;
  reason?: string;
  detectedAt?: string;
}
