/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { InstallmentResponseOperationType } from './installmentResponseOperationType';
import type { InstallmentResponseStatus } from './installmentResponseStatus';
import type { OperationResponse } from './operationResponse';
import type { OperationStatusPhase } from './operationStatusPhase';

export type InstallmentResponse = OperationResponse & {
  id?: string;
  clientBankAccountId?: string;
  amount?: number;
  status?: InstallmentResponseStatus;
  statusHistory?: OperationStatusPhase[];
  createdAt?: string;
  loanId?: string;
  operationType?: InstallmentResponseOperationType;
};
