/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export type LoanRequestInstallmentFrequency = typeof LoanRequestInstallmentFrequency[keyof typeof LoanRequestInstallmentFrequency];


export const LoanRequestInstallmentFrequency = {
  MONTHLY: 'MONTHLY',
  SEMI_ANNUAL: 'SEMI_ANNUAL',
  ANNUAL: 'ANNUAL',
} as const;
