/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { LoanRequestInstallmentFrequency } from './loanRequestInstallmentFrequency';

export interface LoanRequest {
  /** @minimum 0 */
  amount: number;
  /** @minimum 0 */
  termPeriods: number;
  installmentFrequency: LoanRequestInstallmentFrequency;
  /** @minimum 0 */
  interestRate: number;
}
