/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { LoanResponseInstallmentFrequency } from './loanResponseInstallmentFrequency';
import type { LoanResponseStatus } from './loanResponseStatus';
import type { OperationResponse } from './operationResponse';
import type { OperationStatusPhase } from './operationStatusPhase';

export type LoanResponse = OperationResponse & {
  id?: string;
  clientBankAccountId?: string;
  amount?: number;
  status?: LoanResponseStatus;
  statusHistory?: OperationStatusPhase[];
  createdAt?: string;
  termPeriods?: number;
  installmentFrequency?: LoanResponseInstallmentFrequency;
  interestRate?: number;
  paidAmount?: number;
  installmentsPaid?: number;
  nextInstallmentAmount?: number;
  nextInstallmentDate?: string;
  maturityDate?: string;
};
