/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export type LoanResponseInstallmentFrequency = typeof LoanResponseInstallmentFrequency[keyof typeof LoanResponseInstallmentFrequency];


export const LoanResponseInstallmentFrequency = {
  MONTHLY: 'MONTHLY',
  SEMI_ANNUAL: 'SEMI_ANNUAL',
  ANNUAL: 'ANNUAL',
} as const;
