/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export type LoanResponseOperationType = typeof LoanResponseOperationType[keyof typeof LoanResponseOperationType];


export const LoanResponseOperationType = {
  DEPOSIT: 'DEPOSIT',
  TRANSFER: 'TRANSFER',
  LOAN: 'LOAN',
  INSTALLMENT: 'INSTALLMENT',
} as const;
