/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { OperationStatusPhaseStatus } from './operationStatusPhaseStatus';

export interface OperationStatusPhase {
  status?: OperationStatusPhaseStatus;
  createdAt?: string;
  reason?: string;
}
