/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export type OperationEntryResponseOperationDirection = typeof OperationEntryResponseOperationDirection[keyof typeof OperationEntryResponseOperationDirection];


export const OperationEntryResponseOperationDirection = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT',
} as const;
