/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { OperationEntryResponseOperationDirection } from './operationEntryResponseOperationDirection';
import type { OperationEntryResponseOperationType } from './operationEntryResponseOperationType';
import type { OperationEntryResponseStatus } from './operationEntryResponseStatus';

export interface OperationEntryResponse {
  id?: string;
  operationId?: string;
  operationType?: OperationEntryResponseOperationType;
  status?: OperationEntryResponseStatus;
  description?: string;
  amount?: number;
  operationDirection?: OperationEntryResponseOperationDirection;
  createdAt?: string;
}
