/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export type OperationStatusPhaseStatus = typeof OperationStatusPhaseStatus[keyof typeof OperationStatusPhaseStatus];


export const OperationStatusPhaseStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  DENIED: 'DENIED',
  ESCALATED: 'ESCALATED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
} as const;
