/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { OperationEntryResponse } from './operationEntryResponse';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelOperationEntryResponse {
  content?: OperationEntryResponse[];
  page?: PageMetadata;
}
