/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { DepositResponse } from './depositResponse';
import type { InstallmentResponse } from './installmentResponse';
import type { LoanResponse } from './loanResponse';
import type { PageMetadata } from './pageMetadata';
import type { TransferResponse } from './transferResponse';

export interface PagedModelOperationResponse {
  content?: (DepositResponse | InstallmentResponse | LoanResponse | TransferResponse)[];
  page?: PageMetadata;
}
