/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */

export interface SecurityQuestionAnswer {
  /** @minimum 1 */
  questionId?: number;
  /** @minLength 1 */
  answer: string;
}
