/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { SecurityAnswer } from './securityAnswer';

export interface SecurityQuestionAnswersRequest {
  /** @minItems 1 */
  answers: SecurityAnswer[];
}
