/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bank System Core API REST
 * Documentación de la API REST del Core Bancario
 * OpenAPI spec version: 0.0.1
 */
import type { OperationResponse } from './operationResponse';
import type { OperationStatusPhase } from './operationStatusPhase';
import type { TransferResponseOperationType } from './transferResponseOperationType';
import type { TransferResponseStatus } from './transferResponseStatus';

export type TransferResponse = OperationResponse & {
  id?: string;
  clientBankAccountId?: string;
  amount?: number;
  status?: TransferResponseStatus;
  statusHistory?: OperationStatusPhase[];
  createdAt?: string;
  targetBankAccountId?: string;
  concept?: string;
  operationType?: TransferResponseOperationType;
};
